apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: comment-spring-deploy
  name: comment-svc
  namespace: comment-ns
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: comment-spring-deploy
  type: NodePort
status:
  loadBalancer: {}
