apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: front-deploy
  name: front-svc
  namespace: front-ns
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: front-deploy
  type: NodePort
status:
  loadBalancer: {}
