apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: db-rb
  namespace: db-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: db-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: db-engineer
